In [1]:
from plyfile import PlyData
import pandas as pd
import numpy as np

In [2]:
def read_ply_to_dataframe(file_path):
    with open(file_path, 'rb') as file:
        plydata = PlyData.read(file)

    # Extract data from the plydata object
    data = plydata['vertex'].data

    # Create a dictionary to store the data
    ply_dict = {}
    for name in data.dtype.names:
        ply_dict[name] = data[name]

    # Convert the dictionary to a pandas DataFrame
    df = pd.DataFrame(ply_dict)

    return df

In [4]:
read_ply_to_dataframe('/Volumes/T7 Shield/data/data_3d_semantics/train/2013_05_28_drive_0000_sync/dynamic/0000001980_0000002295.ply')

x            y           z  red  green  blue  semantic  \
0      989.987793  3657.305908  115.243500   22     28    17        33   
1      955.236816  3675.143555  115.267700   40     16    17        33   
2      886.795898  3692.617920  115.893799  128    148   155        24   
3      889.303772  3710.722900  115.022499   23     25    27        33   
4      890.269714  3710.578613  115.186096   48     71   107        25   
...           ...          ...         ...  ...    ...   ...       ...   
22108  893.651978  3689.689941  115.769997  128    128   128        24   
22109  893.616028  3689.610107  115.551003  128    128   128        24   
22110  893.591003  3689.439941  116.147003  128    128   128        24   
22111  893.565002  3689.260010  115.753998  128    128   128        24   
22112  893.562012  3689.399902  116.144997  128    128   128        24   

       instance  visible  timestamp  confidence  
0         33029        1       2346    0.937316  
1         33029        1       2314    0.923807  
2         24033        1       2246    0.918915  
3         33029        1       2237    0.860403  
4         25002        1       2234    0.904247  
...         ...      ...        ...         ...  
22108     24033        0       2292    1.000000  
22109     24033        0       2292    1.000000  
22110     24033        0       2292    1.000000  
22111     24033        0       2292    1.000000  
22112     24033        0       2292    1.000000  

[22113 rows x 11 columns]

In [9]:
camera_to_world_path = '../data/data_poses/2013_05_28_drive_0000_sync/cam0_to_world.txt'

carema_to_world_df = pd.read_csv(camera_to_world_path, sep=' ', header=None)

In [10]:
carema_to_world_df

0         1         2         3         4         5         6   \
0          1 -0.938425  0.014711 -0.345172  845.6584  0.345449  0.054392   
1          9 -0.953952  0.005807 -0.299905  845.8253  0.299744  0.056549   
2         14 -0.966197  0.001686 -0.257800  845.9552  0.257463  0.057850   
3         22 -0.975457  0.000603 -0.220193  846.0603  0.219856  0.058036   
4         30 -0.982612  0.002800 -0.185654  846.1557  0.185490  0.059432   
...      ...       ...       ...       ...       ...       ...       ...   
10509  11493 -0.786345  0.090355 -0.611144  779.5217  0.617257  0.073925   
10510  11494 -0.786086  0.089943 -0.611539  779.3807  0.617592  0.073468   
10511  11496 -0.785595  0.091105 -0.611998  779.1451  0.618139  0.071875   
10512  11498 -0.785318  0.090324 -0.612468  778.9784  0.618538  0.072586   
10513  11501 -0.784855  0.090304 -0.613064  778.8342  0.619034  0.069102   

             7         8         9         10        11        12   13  14  \
0     -0.936860  3723.648  0.004993 -0.998412 -0.056123  115.9991  0.0   0   
1     -0.952342  3723.843  0.011430 -0.998383 -0.055685  115.9838  0.0   0   
2     -0.964555  3724.032  0.013288 -0.998324 -0.056327  115.9682  0.0   0   
3     -0.973804  3724.230  0.012193 -0.998314 -0.056743  115.9562  0.0   0   
4     -0.980847  3724.448  0.008287 -0.998229 -0.058917  115.9476  0.0   0   
...         ...       ...       ...       ...       ...       ...  ...  ..   
10509 -0.783281  3134.798 -0.025594 -0.993162 -0.113902  115.6865  0.0   0   
10510 -0.783060  3134.632 -0.025502 -0.993234 -0.113299  115.6866  0.0   0   
10511 -0.782776  3134.363 -0.027328 -0.993244 -0.112779  115.6855  0.0   0   
10512 -0.782395  3134.164 -0.026213 -0.993264 -0.112871  115.6837  0.0   0   
10513 -0.782318  3134.004 -0.028282 -0.993514 -0.110136  115.6813  0.0   0   

        15  16  17  
0      0.0   1 NaN  
1      0.0   1 NaN  
2      0.0   1 NaN  
3      0.0   1 NaN  
4      0.0   1 NaN  
...    ...  ..  ..  
10509  0.0   1 NaN  
10510  0.0   1 NaN  
10511  0.0   1 NaN  
10512  0.0   1 NaN  
10513  0.0   1 NaN  

[10514 rows x 18 columns]

In [23]:
file_path = '../data/data_poses/2013_05_28_drive_0000_sync/cam0_to_world.txt'

# Read the space-separated file into a DataFrame
df = pd.read_csv(file_path, delim_whitespace=True, header=None)

# Extract index and last 16 columns
index_column = df.iloc[:, 0]
matrix_columns = df.iloc[:, -16:]

# Reshape matrix columns into 4x4 matrices
matrices = matrix_columns.values.reshape(-1, 4, 4)

# Calculate the inverse of each matrix
inverse_matrices = [np.linalg.inv(matrix) for matrix in matrices]

# Create a new DataFrame to store the inverse matrices
world_to_cam_df = pd.DataFrame({
    'Index': index_column,
    'Inverse_Matrix': inverse_matrices
})

# Display the new DataFrame
#print(inverse_df)

In [24]:
world_to_cam_df

Index                                     Inverse_Matrix
0          1  [[-0.9384235010973114, 0.3454489590826049, 0.0...
1          9  [[-0.953950629492772, 0.2997432875812914, 0.01...
2         14  [[-0.9661966313226904, 0.2574628192418092, 0.0...
3         22  [[-0.9754552897304742, 0.21985594782775206, 0....
4         30  [[-0.982610415957916, 0.18548999227221044, 0.0...
...      ...                                                ...
10509  11493  [[-0.7863454525817675, 0.6172568621441555, -0....
10510  11494  [[-0.7860848081280822, 0.6175911740548593, -0....
10511  11496  [[-0.7855931864379796, 0.618137838881962, -0.0...
10512  11498  [[-0.7853175612642289, 0.6185373680971742, -0....
10513  11501  [[-0.7848548085599355, 0.6190336654223223, -0....

[10514 rows x 2 columns]

In [25]:
world_to_cam_df.iloc[0]["Inverse_Matrix"]

array([[-9.38423501e-01,  3.45448959e-01,  4.99269310e-03,
        -4.93323757e+02],
       [ 1.47098779e-02,  5.43906172e-02, -9.98411197e-01,
        -9.91562445e+01],
       [-3.45171495e-01, -9.36859951e-01, -5.61240652e-02,
         3.78694420e+03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [26]:
## va
np.linalg.inv(world_to_cam_df.iloc[0]['Inverse_Matrix'])

array([[-9.384250e-01,  1.471056e-02, -3.451720e-01,  8.456584e+02],
       [ 3.454490e-01,  5.439153e-02, -9.368600e-01,  3.723648e+03],
       [ 4.993000e-03, -9.984115e-01, -5.612300e-02,  1.159991e+02],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00]])

# cam to velo transformation

In [22]:
row_data = "0.04307104361 -0.08829286498 0.995162929 0.8043914418 -0.999004371 0.007784614041 0.04392796942 0.2993489574 -0.01162548558 -0.9960641394 -0.08786966659 -0.1770225824 0 0 0 1"

values = list(map(float, row_data.split()))

# Reshape the values into a 3x4 matrix
cam_to_velo = np.array(values).reshape(4, 4)

# Print the matrix
cam_to_velo

array([[ 0.04307104, -0.08829286,  0.99516293,  0.80439144],
       [-0.99900437,  0.00778461,  0.04392797,  0.29934896],
       [-0.01162549, -0.99606414, -0.08786967, -0.17702258],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

# world to velo

### 算 world to velo = cam To velo * world to cam 

In [30]:

world_to_velo_list = [
    np.dot(cam_to_velo, world_to_cam) for world_to_cam in world_to_cam_df['Inverse_Matrix']
]


world_to_velo_df = pd.DataFrame({
    'Index': world_to_cam_df['Index'],
    'world_to_velo': world_to_velo_list
})

In [31]:
world_to_velo_df

Index                                      world_to_velo
0          1  [[-0.38521953326486474, -0.922251749088073, 0....
1          9  [[-0.34005516346333386, -0.9398187502833311, 0...
2         14  [[-0.2983170088445025, -0.9539077916274887, 0....
3         22  [[-0.26119486651628904, -0.9647493115651691, 0...
4         30  [[-0.22732508695529022, -0.9733612073430666, 0...
...      ...                                                ...
10509  11493  [[-0.6500346497057535, -0.7594332137126726, -0...
10510  11494  [[-0.6503798500882121, -0.7591588857386371, -0...
10511  11496  [[-0.6509183318556595, -0.7587126689631927, -0...
10512  11498  [[-0.6513056175648805, -0.7583788775949536, -0...
10513  11501  [[-0.6518770510676284, -0.7579733747884835, -0...

[10514 rows x 2 columns]

In [33]:
world_to_velo_df.iloc[0]["world_to_velo"]

array([[-3.85219533e-01, -9.22251749e-01,  3.25150364e-02,
         3.75693769e+03],
       [ 9.22441007e-01, -3.85835965e-01, -1.52253843e-02,
         6.58712814e+02],
       [ 2.65877512e-02,  2.41290164e-02,  9.99355150e-01,
        -2.28433439e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

# apply world to velo 到 car point cloud，原本car point cloud是世界座標係

In [34]:
car_df = read_ply_to_dataframe("car_point_cloud/car.ply")
car_df

x            y           z  red  green  blue  semantic  \
0       1056.387329  3177.693848  116.197304  255    255   255        26   
1       1056.380127  3177.762451  116.177597  255    255   255        26   
2       1056.525513  3177.733643  116.142799  140    142   145        26   
3       1056.490356  3177.663086  116.097000  255    255   255        26   
4       1056.394287  3177.763428  116.076797  233    220   210        26   
...             ...          ...         ...  ...    ...   ...       ...   
130957  1053.630005  3177.399902  116.285004  128    128   128        26   
130958  1053.619995  3177.379883  116.285004  128    128   128        26   
130959  1053.640015  3177.540039  116.282997  128    128   128        26   
130960  1053.630005  3177.489990  116.283997  128    128   128        26   
130961  1053.650024  3177.649902  116.281998  128    128   128        26   

        instance  visible  timestamp  confidence  
0          26893        1      10341    0.749400  
1          26893        1      10341    0.799349  
2          26893        1      10341    0.829725  
3          26893        1      10341    0.808272  
4          26893        1      10341    0.841420  
...          ...      ...        ...         ...  
130957     26893        0      10355    1.000000  
130958     26893        0      10355    1.000000  
130959     26893        0      10355    1.000000  
130960     26893        0      10355    1.000000  
130961     26893        0      10355    1.000000  

[130962 rows x 11 columns]

In [35]:
print(car_df)

                  x            y           z  red  green  blue  semantic  \
0       1056.387329  3177.693848  116.197304  255    255   255        26   
1       1056.380127  3177.762451  116.177597  255    255   255        26   
2       1056.525513  3177.733643  116.142799  140    142   145        26   
3       1056.490356  3177.663086  116.097000  255    255   255        26   
4       1056.394287  3177.763428  116.076797  233    220   210        26   
...             ...          ...         ...  ...    ...   ...       ...   
130957  1053.630005  3177.399902  116.285004  128    128   128        26   
130958  1053.619995  3177.379883  116.285004  128    128   128        26   
130959  1053.640015  3177.540039  116.282997  128    128   128        26   
130960  1053.630005  3177.489990  116.283997  128    128   128        26   
130961  1053.650024  3177.649902  116.281998  128    128   128        26   

        instance  visible  timestamp  confidence  
0          26893        1      10341

In [36]:
for index, row in car_df.iterrows():
    timestamp = row['timestamp']
    world_to_velo = world_to_velo_df.loc[world_to_velo_df['Index'] == timestamp, 'world_to_velo'].values[0]
    transformed_point = np.dot(world_to_velo, [row['x'], row['y'], row['z'], 1])
    car_df.at[index, 'x'] = transformed_point[0]
    car_df.at[index, 'y'] = transformed_point[1]
    car_df.at[index, 'z'] = transformed_point[2]

In [37]:
car_df

x         y         z  red  green  blue  semantic  instance  \
0        2.618093 -1.942855 -0.835035  255    255   255        26     26893   
1        2.586740 -1.881366 -0.854600  255    255   255        26     26893   
2        2.733119 -1.855111 -0.887182  140    142   145        26     26893   
3        2.726604 -1.933190 -0.933797  255    255   255        26     26893   
4        2.600939 -1.874384 -0.955156  233    220   210        26     26893   
...           ...       ...       ...  ...    ...   ...       ...       ...   
130957 -13.749121 -3.227543 -0.944937  128    128   128        26     26893   
130958 -13.751360 -3.249810 -0.945300  128    128   128        26     26893   
130959 -13.789582 -3.092986 -0.944756  128    128   128        26     26893   
130960 -13.781146 -3.143334 -0.944576  128    128   128        26     26893   
130961 -13.819282 -2.986739 -0.944028  128    128   128        26     26893   

        visible  timestamp  confidence  
0             1      10341    0.749400  
1             1      10341    0.799349  
2             1      10341    0.829725  
3             1      10341    0.808272  
4             1      10341    0.841420  
...         ...        ...         ...  
130957        0      10355    1.000000  
130958        0      10355    1.000000  
130959        0      10355    1.000000  
130960        0      10355    1.000000  
130961        0      10355    1.000000  

[130962 rows x 11 columns]

In [39]:
from plyfile import PlyData, PlyElement

# Example DataFrame (replace this with your actual DataFrame)

def df_to_ply(input_df, name):
# Convert DataFrame to PLY-friendly format
    vertex_count = len(input_df)
    vertex_dtype = [
        ('x', 'f4'),
        ('y', 'f4'),
        ('z', 'f4'),
        ('red', 'u1'),
        ('green', 'u1'),
        ('blue', 'u1'),
        ('semantic', 'i4'),
        ('instance', 'i4'),
        ('visible', 'u1'),
        ('timestamp', 'i4'),
        ('confidence', 'f4'),
    ]

    vertices = np.empty(vertex_count, dtype=vertex_dtype)
    vertices['x'] = input_df['x'].values
    vertices['y'] = input_df['y'].values
    vertices['z'] = input_df['z'].values
    vertices['red'] = input_df['red'].values
    vertices['green'] = input_df['green'].values
    vertices['blue'] = input_df['blue'].values
    vertices['semantic'] = input_df['semantic'].values
    vertices['instance'] = input_df['instance'].values
    vertices['visible'] = input_df['visible'].values
    vertices['timestamp'] = input_df['timestamp'].values
    vertices['confidence'] = input_df['confidence'].values

    # Write data to PLY file
    
    ply_element = PlyElement.describe(vertices, 'vertex')

    # Create PlyData object and save to file
    PlyData([ply_element]).write(name)

In [40]:
df_to_ply(car_df, "car_local.ply")